name: Generate Snake Animation

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Snake Animation
        uses: Platane/snk@v2.2.1  # Mevcut sürümü kullan
        with:
          github_user_name: memoaltinkaynak  # GitHub kullanıcı adını buraya yaz
          outputs: dist/github-contribution-grid-snake.svg
          
      - name: Upload Snake Animation
        uses: actions/upload-artifact@v2
        with:
          name: snake-animation
          path: dist/github-contribution-grid-snake.svg

      - name: Deploy Snake Animation
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
